version: 2
updates:
  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      # Check for updates to pip dependencies at 9am UTC
      time: "09:00"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "django"
        # Ignore all updates for Django. You may want to specify a version range
        # if you only want to ignore updates that go beyond a certain version.
        versions: ["*"]
