"""
Django's settings for backend_service project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
# pylint: disable=unused-wildcard-import,wildcard-import
from backend_service.settings.base import *  # noqa: F403  # NOSONAR

EMAIL_BACKEND = "communications.services.email.EmailBackend"
