"""
Django's settings for backend_service project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
# pylint: disable=unused-wildcard-import,wildcard-import
from backend_service.settings.base import *  # noqa: F403 # NOSONAR

DEBUG = False
PERFORMANCE_ANALYSIS = False

# Pop the 0th item from the MIDDLEWARE list which is the HealthCheckMiddleware
MIDDLEWARE.pop(0)

SECONDARY_POSTGRES_HOST = None

WHITELISTED_IP_ADDRESSES = ["*"]

REST_FRAMEWORK["DEFAULT_THROTTLE_CLASSES"] = []
REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {}

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": PRIMARY_POSTGRES_HOST,
        "NAME": POSTGRES_DB,
        "USER": POSTGRES_USER,
        "PASSWORD": POSTGRES_PASSWORD,
        "PORT": POSTGRES_PORT,
    }
}
